linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
  nolintlint:
    require-explanation: true
    require-specific: true
  revive:
    rules:
      - name: var-naming
        arguments: [["Id"], ["ID"]]
  stylecheck:
    checks:
      [
        "all",
        "-ST1000",
        "-ST1003",
        "-ST1016",
        "-ST1020",
        "-ST1021",
        "-ST1022",
        "-ST1023",
      ]

linters:
  enable-all: true
  disable:
    - interfacer
    - scopelint
    - golint
    - maligned
    - exhaustivestruct
    - ifshort
    - gochecknoglobals
    - revive
    - paralleltest
run:
  issues-exit-code: 1
