name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Lint (golangci-lint)
        run: golangci-lint run ./...

      - name: Format
        run: gofumpt -w -l ./...

      - name: Test
        run: go test -v ./...
