name: Test

env:
  MONGO_DB__USERNAME: ${{ secrets.MONGO_DB__USERNAME }}
  MONGO_DB__PASSWORD: ${{ secrets.MONGO_DB__PASSWORD }}
  MONGO_DB__CONNECTION_URL: ${{ secrets.MONGO_DB__CONNECTION_URL }}
  MONGO_DB__DATABASE_NAME: ${{ secrets.MONGO_DB__DATABASE_NAME }}
  MONGO_DB__COLLECTIONS__USERS_NAME: ${{ secrets.MONGO_DB__COLLECTIONS__USERS_NAME }}
  MONGO_DB__COLLECTIONS__BUSYTIMES_NAME: ${{ secrets.MONGO_DB__COLLECTIONS__BUSYTIMES_NAME }}
  MONGO_DB__COLLECTIONS__GUILDS_NAME: ${{ secrets.MONGO_DB__COLLECTIONS__GUILDS_NAME }}
  BUSYBEE_BOT__APP_ID: ${{ secrets.BUSYBEE_BOT__APP_ID }}
  BUSYBEE_BOT__TOKEN: ${{ secrets.BUSYBEE_BOT__TOKEN }}
  GOURD_BOT__APP_ID: ${{ secrets.GOURD_BOT__APP_ID }}
  GOURD_BOT__TOKEN: ${{ secrets.GOURD_BOT__TOKEN }}

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
